# introduciton to R: practice
# author: shuo zhang, group628.llc 

# Question 1:
#Each new term in the Fibonacci sequence is generated by adding the previous two 
# terms. Starting with 1 and 2, the first 10 Fibonacci numbers are:
#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...
# Consider all the Fibonacci numbers whose values do not exceed four million. 
# Find the sum of even-valued terms among them.
i = 2
x = 1:2
sum = 0 
while (x[i] < 4e6){
  if (x[i] %% 2 == 0){
    sum = sum + x[i]
  }
  x[i+1] = x[i] + x[i-1]
  i = i + 1
}
sum

# Question 2:
# Write some R code to generate a vector with the following elements, 
# without using loops .
# "aa" "ba" "ca" "da" "ea" "ab" "bb" "cb" "db" "eb" "ac" "bc" "cc" "dc" "ec"
# "ad" "bd" "cd" "dd" "ed" "ae" "be" "ce" "de" "ee"

list<-c("a","b","c","d","e")
list1<-rep(list,5)
list1
list2<-rep(list,each=5)
list2
list3<-paste(list1,list2)
list3


